project:
  type: book
  output-dir: docs

book:
  title: "Mastering Bioinformatics"
  author: "Noname"
  date: "1/24/2026"
  chapters:
    - index.qmd
    - Mastering_Python_for_Bioinformatics.qmd
    - Python_for_Biologists_A_Complete_Programming_Course.qmd
    - Managing_Your_Biological_Data_with_Python.qmd
    - PythonMastery.qmd
    - Bioinformatics_in_Cancer_and_Cancer_Therapy.md
    - Bioinformatics_and_Computational_Biology_Solutions_Using_R_and_Bioconductor.md
    - Bioinformatics_and_Machine_Learning_for_Cancer_Biology.md
    - Bioinformatics_and_Drug_Discovery.md

bibliography: references.bib

format:
  html:
    theme:
      - flatly
      - brand
    number-sections: false

execute:
  freeze: auto
