project:
  type: book
  output-dir: docs

book:
  title: "Mastering Bioinformatics"
  author: "Noname"
  date: "1/24/2026"
  chapters:
    - index.qmd
    - PythonMastery.qmd
    - Mastering_Python_for_Bioinformatics.qmd
    - Python_for_Biologists_A_Complete_Programming_Course.qmd
    - Managing_Your_Biological_Data_with_Python.qmd
    - Sequence_Analysis_with_Biopython.qmd
    - Bioinformatics_in_Cancer_and_Cancer_Therapy.md
    - Bioinformatics_and_Computational_Biology_Solutions_Using_R_and_Bioconductor.md
    - Bioinformatics_and_Drug_Discovery.md
    - Deep_Learning_for_Biology_Harness_AI_to_Solve_Real_World_Biology_Problems.qmd
    - Large_Language_Models_in_Protein_Bioinformatics.md
    - Streamlining_Your_Research_Laboratory_with_Python.md

bibliography: references.bib

format:
  html:
    theme:
      - flatly
      - brand
    number-sections: false

execute:
  freeze: auto
